name: nf-core-rnaseq-3.4

channels:
  - conda-forge
  - bioconda
  - mvdbeek
  - defaults

dependencies:
  - conda-forge::r-base=4.0.3
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-rcolorbrewer=1.1_2
  - conda-forge::r-pheatmap=1.0.12
  - bioconda::bioconductor-deseq2=1.34.0
  - bioconda::bioconductor-dupradar=1.24.0
  - bioconda::bioconductor-summarizedexperiment=1.24.0
  - bioconda::bioconductor-tximeta=1.12.0
  - bioconda::bioconductor-iranges=2.28.0
  - bioconda::bioconductor-genomeinfodb=1.30.0
  - bioconda::bioconductor-biobase=2.54.0
  - bioconda::bioconductor-s4vectors=0.32.0
  - bioconda::bioconductor-biocgenerics=0.40.0
  - conda-forge::r-ggplot2=3.3.5

  - bioconda::gffread
  - bioconda::bbmap=38.93
  - bioconda::hisat2=2.2.1
  - bioconda::qualimap
  - bioconda::rsem
  - bioconda::rseqc
  - bioconda::salmon
  - bioconda::sortmerna
  - bioconda::star
  - bioconda::stringtie
  - bioconda::umi_tools
  - bioconda::picard
  - mvdbeek::ucsc_tools
